
import dal.DBContext;
import entity.Book;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GL552VW
 */
public class BookMaster extends javax.swing.JFrame {
   DBContext context = new DBContext();
   ArrayList<Book> books = context.getBooks();
    /**
     * Creates new form BookMaster
     */
    public BookMaster() {
         initComponents();
         loadDataToTable();
    }
    
    private void loadDataToTable() {
      
        ArrayList<Book> books = context.getBooks();

        Object[] columns = {"book_id", "book_title", "book_author", "book_publish_year", "book_category" ,"book_keyword","book_status"};
        Object[][] data = new Object[books.size()][columns.length];
        for (int i = 0; i < books.size(); i++) {
            entity.Book s = books.get(i);
            data[i][0] = s.getBook_id();
            data[i][1] = s.getBook_title();
            data[i][2] = s.getBook_author();
            data[i][3] = s.getBook_publish_year();
            data[i][4] = s.getBook_category();
            data[i][5] = s.getBook_keyword();
            data[i][6] = s.getBook_status();
            
            
        }
        DefaultTableModel model = new DefaultTableModel(data, columns);
        tblBook.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sror = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnOrderList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BookMaster\n");

        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Sror.setViewportView(tblBook);

        jLabel1.setFont(new java.awt.Font("PMingLiU", 1, 26)); // NOI18N
        jLabel1.setText("Spending at least 30 minutes a day reading books will help your brain a lot");

        btnOrder.setText("UpdateBook");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel2.setText("Exit Book:");

        btnOrderList.setText("ListBook");
        btnOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2)
                        .addGap(88, 88, 88)
                        .addComponent(btnOrderList)
                        .addGap(142, 142, 142)
                        .addComponent(btnOrder)
                        .addGap(149, 149, 149)
                        .addComponent(btnClose)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrder)
                    .addComponent(jLabel2)
                    .addComponent(btnClose)
                    .addComponent(btnOrderList))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sror)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sror, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderListActionPerformed
        OrderList b = new OrderList(this, true);
        b.setVisible(true);
    }//GEN-LAST:event_btnOrderListActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        int index = tblBook.getSelectedRow();
        int click = JOptionPane.showConfirmDialog(this, "Do you want order this book?", null, JOptionPane.YES_NO_OPTION);
        if (index != -1 && click == JOptionPane.YES_OPTION) {
            //            int book_id = (Integer) tblBook.getModel().getValueAt(index, 0);
             int id = (int) tblBook.getModel().getValueAt(index, 0);
                   //     String book_title = (String) tblBook.getModel().getValueAt(index, 1);
            //            String book_author = (String) tblBook.getModel().getValueAt(index, 2);
            //            String book_publish_year = (String) tblBook.getModel().getValueAt(index, 3);
            //            String book_category = (String) tblBook.getModel().getValueAt(index, 4);
            //            String book_keyword = (String) tblBook.getModel().getValueAt(index, 5);
            //            String book_status = (String) tblBook.getModel().getValueAt(index, 6);
            //
            //            Book book = new Book(book_id, book_title, book_author, book_publish_year, book_category,book_keyword,book_status);
            //            context.insertBook(book);
            InsertBook us = new InsertBook(this, true,id);
            us.setVisible(true);
//           UpdateBook us = new UpdateBook(this, true, id);
//            us.setVisible(true);
           
            //  loadDataToTable();
            //  context.insertBook(new Book(Integer.parseInt(book_id, book_title, book_author, book_publish_year, book_category,book_keyword,book_status)));
//            lbl3.setText("Order successfully!");

        }

    }//GEN-LAST:event_btnOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Sror;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnOrderList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tblBook;
    // End of variables declaration//GEN-END:variables
}
